#!/bin/bash
#使用start启动脚本，使用stop停止脚本
if(($#!=1))
then
	echo 请输入start或stop!
	exit;
fi

if [ $1 = start ]
then
	ssh hadoop104 "nohup flume-ng agent -c $FLUME_HOME/conf/ -n a1 -f $FLUME_HOME/myagents/f2.conf -Dflume.root.logger=INFO,console > /home/atguigu/f2.log 2>&1 &"

elif [ $1 = stop ]
then 
	ssh hadoop104 "ps -ef  | grep f2.conf | grep -v grep | awk  '{print \$2}' | xargs kill -9"

else
	echo 请输入start或stop!
fi

 
	
