#!/bin/bash
#在hadoop102,hadoop103产生日志
for i in hadoop102 hadoop103
do
    ssh $i java -cp /opt/module/log-collector-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.atguigu.appclient.AppMain $1 $2 > /dev/null 2>&1 &	
done
